config/routes.rb
Rails.application.routes.draw do
  get 'top/main'
  post 'top/login'
  get 'top/logout'
  resources :users
  resources :tweets
  resources :likes, only: [:create, :destroy]
  
  root 'tweets#index'
  
  #get 'top/main'
  #get 'top/login'
  #get 'top/logout'
  #get 'tweets/index'
  #get 'tweets/new'
  #get 'tweets/create'
  #get 'tweets/destroy'
  #get 'tweets/show'
  #get 'tweets/edit'
  #get 'tweets/update'
  #get 'index/new'
  #get 'index/create'
  #get 'index/destroy'
  #get 'index/show'
  #get 'index/edit'
  #get 'index/update'
  #resources :users
  #resources :users
  #root 'users#index'
  
  #get 'users/index'
  #get 'users/new'
  #post 'users/create'
  #delete 'users/:id', to: 'users#destroy'
  
  #resources :tweets
  
  #post 'top/login'
  #get 'top/logout'
  
  #resources :top
  #resources :likes
  
  
  #resources :users, :tweets, :top, :likes
  #root 'users#index'
  
  #get 'users/index'
  #get 'users/new'
  #post 'users/create'
  #delete 'users/:id', to: 'users#destroy'
  
  #get 'tweets/index'
  #get 'tweets/new'
  #post 'tweets/create'
  #delete 'tweets/:id', to: 'tweets#destroy'
  
  #get 'tweets/show'
  #get 'tweets/edit'
  #post 'tweets/update'
  
  #get 'top/main'
  #get 'top/login'
  #get 'top/logout'
  
  #get 'likes/create'
  #get 'likes/destroy'
  #get 'users/:id', to: 'users#show', as: :users
   
   
   
   
  #get 'users/index'
  #resources :users
  
  #get 'tweets/index'
  #resources :tweets
  
  #root 'top#main'
  #get 'top/login_form'
  #post 'top/login'
  #get 'top/logout'
  
  #resources :likes
  #get 'users/:id', to: 'users#show', as: :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :likes ,dependent: :destroy #ツイートを消すといいねも消える
    has_many :like_users, through: :likes, source: :user
    
    def like(user)
        likes.create(user_id: user.id)
    end

    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end

    def liked?(user) #いいね済みか調べる(true / false)
        like_users.include?(user)
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets, dependent: :destroy #ユーザを消すとツイートも消える
    has_many :likes, dependent: :destroy #ユーザを消すとツイートも消える
    has_many :like_tweets, through: :likes, source: :tweet
    
    validates :password, presence: true, confirmation: true
    
    attr_accessor :password, :password_confirmation
    
    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
            @password = val
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
private
    helper_method :current_user
    def current_user
        if session[:login_uid]
            User.find_by(uid: session[:login_uid])
        end
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        unless tweet.liked?(current_user)
            tweet.like(current_user)
        end
        redirect_to root_path
    end
    
    def destroy
        tweet = Tweet.find(params[:id])
        if tweet.liked?(current_user)
            tweet.unlike(current_user)
        end
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
require 'bcrypt'
class TopController < ApplicationController
  def main
    render "login"
  end
  
  def login
    user = User.find_by(uid: params[:uid])
    if user != nil
      login_password = BCrypt::Password.new(user.pass)
      if login_password == params[:pass] #←login_password.==(“my password”)
        session[:login_uid] = user.uid
        redirect_to root_path
      else
        render "login"
      end
    end
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
      @tweets = Tweet.all
      @tweet = Tweet.new
    end
    
    def new
        @user = User.new
    end
  
    def create
      tweet = Tweet.new(message: params[:tweet][:message])
      tweet.user_id = current_user.id
      tweet.save
      redirect_to root_path
    end
    
    def destroy
        Tweet.find(params[:id]).destroy
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    #p = BCrypt::Password.create(params[:user][:pass])
    #user = User.new(uid: params[:user][:uid], pass: p, age: params[:user][:age])
    @user = User.new(uid: params[:user][:uid], password: params[:user][:password], password_confirmation: params[:user][:password_confirmation], age: params[:user][:age])
    #user.save
    #redirect_to users_path
    
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
    
  end
  
  #render 'top/login'

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>

app/views/tweets/edit.html.erb
<% if @tweet.errors.present? %>
    <h3>エラーがあります。</h3>
    <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @tweet , url: {action: :update} do |f| %>
    <%= f.label :message, 'メッセージ' %>
    <%= f.text_field :message %>
    <%= f.submit '更新' %>
<% end %>

app/views/tweets/index.html.erb
<% @tweets.each do |e| %>
<p>
  <%= e.message %>
  
  <% if current_user %>
    <%= link_to "削除", tweet_path(e), data: { "turbo-method": :delete} %>
    <% if e.liked?(current_user) %>
      <%= link_to 'いいね削除', like_path(e), data: { "turbo-method": :delete} %>
    <% else %>
      <%= link_to 'いいね', likes_path(tweet_id: e.id), data: { "turbo-method": :post} %>
    <% end %>
  <% end %>
</p>
<% end %>

<hr>

<%= form_for @tweet, url: {action: :create} do |f| %>
  <%= f.label :message, 'message' %>
  <%= f.text_field :message %>
  <%= f.submit "ツイート" %>
<% end %>

<hr>

<% if session[:login_uid] %>
  <p><%= link_to 'ログアウト', top_logout_path %></p>
<% else %>
  <p><%= link_to 'ログイン', top_main_path %></p>
<% end %>

<p><%= link_to 'ユーザ一覧', users_path %></p>

app/views/users/_user.html.erb
<p><%= user.uid %></p>
<p><%= user.age %></p>

app/views/users/create.html.erb
<h1>ユーザー登録が成功しました</h1>
<p>新しいユーザーアカウントが正常に作成されました。ようこそ！</p>

<%= link_to 'ホームへ', root_path %>

app/views/users/destroy.html.erb
<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.uid %>
      <%= link_to "削除", user, method: :delete, data: { confirm: "本当に削除しますか？" } %>
    </li>
  <% end %>
</ul>

app/views/users/index.html.erb
<% @users.each do |e| %>
<p>
    UID： <%= e.uid %><br>
    PASS： <%= e.pass %><br>
    AGE： <%= e.age %><br>
    <%= link_to "削除", user_path(e), data: { "turbo-method": :delete } %>
</p>
<% end %>

<p>
    <%= link_to "新規登録", new_user_path %>
</p>

<hr>
<p>
    <%= link_to "ツイート一覧", tweets_path %>
</p>

app/views/users/new.html.erb
<%= form_for @user, url: {action: :create} do |f| %>
  <p>
    <%= f.label :uid, 'UID' %>
    <%= f.text_field :uid %>
  </p>

  <p>
    <%= f.label :password, 'PASS' %>
    <%= f.password_field :password %>
  </p>
  
  <p>
    <%= f.label :password_confirmation, 'パスワード(確認)：' %>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.label :age, 'AGE' %>
    <%= f.text_field :age %>
  </p>

  <p>
    <%= f.submit "登録" %>
  </p>
<% end %>


<!--<h1>Users#new</h1>-->
<!--<p>Find me in app/views/new.html.erb</p>-->